/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// Where the led is connected?
// Port:C
// Pin:13
#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

#define PERIPH_BASE	       (0x40000000UL)
#define APB2_OFFSET        (0x00010000UL)
#define APB2_BASE	       (PERIPH_BASE + APB2_OFFSET)
#define AHB_OFFSET         (0x00018000UL)
#define AHB_BASE           (PERIPH_BASE + AHB_OFFSET)

#define GPIOC_OFFSET       (0x00001000UL)
#define GPIOC_BASE	       (APB2_BASE + GPIOC_OFFSET)
#define RCC_OFFSET         (0x00009000UL)
#define RCC_BASE           (AHB_BASE + RCC_OFFSET)

#define RCC_APB2ENR_OFFSET (0x18UL)
#define RCC_APB2ENR_BASE   (RCC_BASE + RCC_APB2ENR_OFFSET)

#define GPIOC_CRH_OFFSET   (0x04UL)
#define GPIOC_CRH          (GPIOC_BASE + GPIOC_CRH_OFFSET)
#define GPIOC_BSRR_OFFSET  (0x10UL)
#define GPIOC_BSRR         (GPIOC_BASE + GPIOC_BSRR_OFFSET)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(uint64_t n) {
	for (uint64_t i = 0; i < n; i++) {
		for (uint64_t j = 0; j < n; j++) {
			;
		}
	}
}

int main(void) {
	volatile uint32_t *rcc_apb2enr = (volatile uint32_t *) RCC_APB2ENR_BASE;
	*rcc_apb2enr |= 0b1 << 4; // IOPC EN
	volatile uint32_t *gpioc_crh = (volatile uint32_t *) GPIOC_CRH;
	*gpioc_crh &= ~(0xf << 20); // clear bits for pin 13
	*gpioc_crh |= (0b0011 << 20);
	volatile uint32_t *gpioc_bsrr = (volatile uint32_t *) GPIOC_BSRR;
	printf("Hello\n");

	while (true) {
		*gpioc_bsrr |= (0b1 << 29);
		delay(300);
		*gpioc_bsrr |= (0b1 << 13);
		delay(300);
	}
}
